[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "bash"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = [
    "php artisan config:cache",
    "php artisan route:cache",
    "chmod +x init-railway.sh"
]

[start]
cmd = "./init-railway.sh"
